default:
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: frank.ficnar@gmail.com
      mongodb:
        host: localhost
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email

staging:
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: ~
      mongodb:
        host: i-9e08ccfc
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email

production:
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: ~
      mongodb:
        host: i-51d50f34
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email
