default:
  ruby_app:
    application:
      _class: "Pike::Application"
    language:
      default: "en"
      paths:
        - "#{RubyApp::ROOT}/translations"
        - "#{Pike::ROOT}/translations"
    log:
      path: "#{Pike::ROOT}/process/log/application.log"
    session:
      _class: "Pike::Session"
      expires: 900
      interval: 15
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: frank.ficnar@gmail.com
        from: '"Pike" <virtualpatterns@sympatico.ca>'
      mongodb:
        host: localhost
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email

staging:
  ruby_app:
    application:
      _class: "Pike::Application"
    language:
      default: "en"
      paths:
        - "#{RubyApp::ROOT}/translations"
        - "#{Pike::ROOT}/translations"
    log:
      path: "#{Pike::ROOT}/process/log/application.log"
    session:
      _class: "Pike::Session"
      expires: 900
      interval: 15
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: ~
        from: '"Pike" <virtualpatterns@sympatico.ca>'
      mongodb:
        host: localhost
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email

production:
  ruby_app:
    application:
      _class: "Pike::Application"
    language:
      default: "en"
      paths:
        - "#{RubyApp::ROOT}/translations"
        - "#{Pike::ROOT}/translations"
    log:
      path: "#{Pike::ROOT}/process/log/application.log"
    session:
      _class: "Pike::Session"
      expires: 900
      interval: 15
  pike:
    application:
      format:
        date:
          long: %c
          short: %a %b %-d
      amazon:
        access_key: ABC
        secret_key: DEF
      mail:
        to: ~
        from: '"Pike" <virtualpatterns@sympatico.ca>'
      mongodb:
        host: i-51d50f34
        port: 27017
        database: pike
    elements:
      pages:
        authentication:
          open_id:
            google_authentication_page:
              identifier: https://www.google.com/accounts/o8/id
              attributes:
                email: http://schema.openid.net/contact/email
