require 'rubygems'
require 'railsless-deploy'
load    'config/deploy'

namespace :pike do

  desc 'Print version information'
  task :version do
    run "cd /var/www/pike/current && bundle exec rake pike:version"
  end

  desc 'Start'
  task :start, :roles => :application do
    find_and_execute_task('pike:daemon:start')
    run "cd /var/www/pike/current && bundle exec rake pike:start[#{servers}]"
  end

  desc 'Stop'
  task :stop, :roles => :application do
    run "cd /var/www/pike/current && bundle exec rake pike:stop"
    find_and_execute_task('pike:daemon:stop')
  end

  desc 'Restart'
  task :restart do
    find_and_execute_task('pike:stop')
    find_and_execute_task('pike:start')
  end

  desc 'Update without stop/start'
  task :update_only do
    find_and_execute_task('deploy:update')
    #sudo 'gem update'
    find_and_execute_task('pike:data:migrate')
  end

  desc 'Update'
  task :update do
    find_and_execute_task('pike:stop')
    find_and_execute_task('pike:update_only')
    find_and_execute_task('pike:start')
  end

  namespace :daemon do

    desc 'Start the daemon'
    task :start, :roles => :data do |task|
      run "cd /var/www/pike/current && bundle exec rake pike:daemon:start"
    end

    desc 'Stop the daemon'
    task :stop, :roles => :data do |task|
      run 'cd /var/www/pike/current && bundle exec rake pike:daemon:stop'
    end

  end

  namespace :data do

    desc 'Dump database to ./dump.tgz'
    task :dump, :roles => :data do
      run 'cd /var/www/pike/current && bundle exec rake pike:data:dump'
      download '/var/www/pike/current/dump.tgz', '.', :via=> :scp
    end

    desc 'Restore dumped database from ./dump.tgz'
    task :restore, :roles => :data do
      upload './dump.tgz', '/var/www/pike/current', :via=> :scp
      run 'cd /var/www/pike/current && bundle exec rake pike:data:restore'
    end

    namespace :identities do

      desc 'Expire all'
      task :expire_all, :roles => :data do
        run 'cd /var/www/pike/current && bundle exec rake pike:data:identities:expire_all'
      end

    end

    desc 'Migrate'
    task :migrate, :roles => :data do
      run 'cd /var/www/pike/current && bundle exec rake pike:data:migrate:all'
    end

  end

end
