require 'rubygems'
require 'railsless-deploy'

load    'config/deploy'

namespace :pike do

  desc 'Print version information'
  task :version do
    run('cd /var/www/pike/current && bundle exec rake pike:version')
  end

  desc 'Update without stop/start'
  task :update_only do
    find_and_execute_task('deploy:update')
    find_and_execute_task('pike:data:migrate')
  end

  desc 'Update'
  task :update do
    find_and_execute_task('pike:process:stop')
    find_and_execute_task('pike:update_only')
    find_and_execute_task('pike:process:start')
    find_and_execute_task('deploy:cleanup')
  end

  desc 'Rollback without stop/start'
  task :rollback_only do
    find_and_execute_task('deploy:rollback')
  end

  desc 'Rollback'
  task :rollback do
    find_and_execute_task('pike:process:stop')
    find_and_execute_task('pike:rollback_only')
    find_and_execute_task('pike:process:start')
  end

  namespace :process do

    desc 'Start the server(s)'
    task :start, :roles => :application do
      run("cd /var/www/pike/current && bundle exec rake pike:process:cron:install")
      find_and_execute_task('pike:process:daemon:start')
      run("cd /var/www/pike/current && bundle exec rake pike:process:thin:start[true,#{servers}]")
    end

    desc 'Stop the server(s)'
    task :stop, :roles => :application do
      run('cd /var/www/pike/current && bundle exec rake pike:process:thin:stop')
      find_and_execute_task('pike:process:daemon:stop')
      run("cd /var/www/pike/current && bundle exec rake pike:process:cron:uninstall")
    end

    desc 'Restart the server(s)'
    task :restart do
      find_and_execute_task('pike:process:stop')
      find_and_execute_task('pike:process:start')
    end

    namespace :daemon do

      desc 'Start the daemon'
      task :start, :roles => :data do |task|
        run "cd /var/www/pike/current && bundle exec rake pike:process:daemon:start"
      end

      desc 'Stop the daemon'
      task :stop, :roles => :data do |task|
        run 'cd /var/www/pike/current && bundle exec rake pike:process:daemon:stop'
      end

    end

  end

  namespace :data do

    desc 'Backup the database'
    task :backup, :roles => :data do
      stamp = "#{stage}.#{Time.now.strftime('%Y%m%d%H%M%S')}"
      run "cd /var/www/pike/current && bundle exec rake pike:data:backup['#{stamp}']"
      download "/var/www/pike/current/pike.#{stamp}.tar.gz", '.', :via=> :scp
      run "rm -f /var/www/pike/current/pike.#{stamp}.tar.gz"
    end

    desc 'Restore a database backup using -s stamp=?'
    task :restore, :roles => :data do
      upload "./pike.#{stamp}.tar.gz", '/var/www/pike/current', :via=> :scp
      run "cd /var/www/pike/current && bundle exec rake pike:data:restore['#{stamp}']"
      run "rm -f /var/www/pike/current/pike.#{stamp}.tar.gz"
    end

    namespace :identities do

      desc 'Expire all identities'
      task :expire_all, :roles => :data do
        run 'cd /var/www/pike/current && bundle exec rake pike:data:identities:expire_all'
      end

    end

    desc 'Run all migrations'
    task :migrate, :roles => :data do
      run 'cd /var/www/pike/current && bundle exec rake pike:data:migrate:all'
    end

    namespace :indexes do

      desc 'Create indexes'
      task :create, :roles => :data do
        run 'cd /var/www/pike/current && bundle exec rake pike:data:indexes:create_all'
      end

    end

  end

end
